# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.generic.models


class Migration(migrations.Migration):

    replaces = [('customer_management', '0001_initial'), ('customer_management', '0002_auto_20160507_1439'), ('customer_management', '0003_auto_20160507_1454'), ('customer_management', '0004_auto_20160510_0913'), ('customer_management', '0005_auto_20160510_1121'), ('customer_management', '0006_auto_20160510_1301'), ('customer_management', '0007_customer_avatar'), ('customer_management', '0008_auto_20160512_0948')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('iban', localflavor.generic.models.IBANField(False, None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('password', models.CharField(default=1, max_length=128, verbose_name='password')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer_management.CustomerAdmin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
