# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 14:39
from __future__ import unicode_literals

from django.db import migrations
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='iban',
            field=localflavor.generic.models.IBANField(False, None),
        ),
    ]
