# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0004_auto_20160510_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeradmin',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customeradmin',
            name='last_name',
        ),
    ]
